-- Niepowtarzaloœæ odczytów --

-- SET TRANSACTION ISOLATION LEVEL READ COMMITTED;
SET TRANSACTION ISOLATION LEVEL REPEATABLE READ;

DROP TABLE IF EXISTS Ludzie 
GO

CREATE TABLE Ludzie (Imie VARCHAR(20), Nazwisko VARCHAR(20), Wiek INT)
INSERT INTO Ludzie VALUES('Tomasz', 'Kowalski',    19)
INSERT INTO Ludzie VALUES('Arnold', 'Wonsik',    49)

GO


-- T1
BEGIN TRAN
SELECT * FROM Ludzie
WAITFOR DELAY '00:00:05'
SELECT * FROM Ludzie
ROLLBACK
GO

-- T2

BEGIN TRAN
UPDATE Ludzie SET Wiek = 50 WHERE Imie = 'Tomasz'
COMMIT
GO
